from pptx.dml.color import RGBColor
TITLE = "CAT FRIENDLY GUIDE"
SUBTITLE = "Make Your Cat Get Used To A New Environment"

INPUT_FILENAME = "test/cat.pdf"
OUTPUT_FILENAME = "output.pptx"

TMP_DIRECTORY = "tmp"
FONT_FAMILY = "Inter"
PARAGRAPH_FONT_SIZE = 18
MAX_WORD_PER_PAGE_DEFAULT = 70
MAX_WORD_PER_PAGE_WITH_IMAGE = 30
HEADER_COLOR = RGBColor(0, 0, 0)
MAX_TABLE_LENGTH_CM = 25
MAX_TABLE_HEIGHT_CM = 15
INCH_TO_CM_MULTIPLIER = 914400/360000
PADDING_TOP = 50
HEADER_COLOR = RGBColor(0, 0, 255)

IGNORE_TOP = 50
IGNORE_BOTTOM = 0
