from pptx.dml.color import RGBColor
TITLE = "RUST"
INPUT_FILENAME = "test/hacknrollSimple.pdf"
OUTPUT_FILENAME = "output.pptx"

TMP_DIRECTORY = "tmp"
FONT_FAMILY = "Inter"
PARAGRAPH_FONT_SIZE = 18
MAX_WORD_PER_PAGE_DEFAULT = 120
MAX_WORD_PER_PAGE_WITH_IMAGE = 30
HEADER_COLOR = RGBColor(0, 0, 0)
MAX_TABLE_LENGTH_CM = 25
MAX_TABLE_HEIGHT_CM = 15
INCH_TO_CM_MULTIPLIER = 914400/360000